### ISSUE TITLE
Add documentation for the GraphQL API

### ISSUE THREAD

**Issue by NeroNemesis** [SEG4510-Team-63/springharvest#12]

**Comment by MysticKora** [comment]
GraphQL Auto-Documentation Explorers exist (GraphiQL)
GraphiQL  is an in-browser Integrated Development Environment (IDE) for exploring GraphQL. This makes interacting with your GraphQL much more streamlined and easy to navigate. It also makes programming in GraphQL easier thanks to a detailed GUI.

GraphiQL features a window that shows all of the possible queries, fields, mutations, types, and if they’re required. GraphiQL also stays synced with GraphQL, removing any depreciated fields and types from the documentation. You won’t have to worry about writing defunct code, so everything you script is going to work.
